### ISSUE TITLE
'NODE_ENV' is not recognized on Windows.

### ISSUE THREAD

**Issue by uniankit** [pbowyer/ionic-cascading-config#1]
I tried to run your project on Android, but it failed saying 'NODE_ENV' is not recognized.
Screenshot attached.
Please look into it. 

![issue](https://user-images.githubusercontent.com/29115484/29003136-c07e0840-7ace-11e7-8728-586b0b239564.JPG)

**Comment by pbowyer** [comment]
Thanks for the report, this is a Windows issue; it doesn't like that way of setting environment variables. 

I'll fix this today.

**Comment by pbowyer** [comment]
@uniankit This should be fixed in e8555a794e932c8ccef1bc1b6b25af2a81682d5d. Please test and confirm - I'll leave the ticket open for 72 hours for your feedback.

**Comment by uniankit** [comment]
Thanks @pbowyer for your clarification and fix. I tested and it is working perfectly for me.

**Comment by pbowyer** [comment]
Great to hear it works, closing the issue!
