### ISSUE TITLE
No longer works with ionic app scripts v3

### ISSUE THREAD

**Issue by phildotdev** [pbowyer/ionic-cascading-config#4]
Hi,

Thanks for making this repo, I have been using it for a while to great effect. Unfortunately it has stopped working when upgrading to ionic-app-scripts v3.0.0. I believe this is because they have upgraded the code to export different configs, see: https://github.com/ionic-team/ionic-app-scripts/blob/master/config/webpack.config.js#L143-L146

Have you got any ideas how to get this working? Thanks.

**Comment by marcorinck** [comment]
I just stumbled upon this too. The fix is somewhat easy. You have to update config/webpack.config.js to something like this:

````javascript
var webpack = require('webpack');
var merge = require('webpack-merge');

var webpackConfig = require('../node_modules/@ionic/app-scripts/config/webpack.config');

var plugins = [
    new webpack.EnvironmentPlugin({
      NODE_ENV: undefined
    }),
    new webpack.NormalModuleReplacementPlugin(/\.\/environments\/environment\.default/, function (resource) {
      //console.log('NODE_ENV', process.env.NODE_ENV);
      if (process.env.NODE_ENV !== undefined) {
        var env = process.env.NODE_ENV;
        console.log('Rewriting ', resource.request);
        // @TODO try to generalise the regex using negative lookaheads https://stackoverflow.com/questions/977251/regular-expressions-and-negating-a-whole-character-group
        resource.request = resource.request.replace(/\.\/environments\/environment\.default/, '\.\/environments/environment.' + env);
        console.log('to        ', resource.request);
      } else {
        console.log('No environment specified. Using `default`');
      }
    })
  ]
});

module.exports = {
	dev: merge(webpackConfig.dev, {
		plugins: plugins
	}),
	prod: merge(webpackConfig.prod, {
		plugins: plugins
	})
};
````

As the original webpack is exporting its config as an object with dev and prod keys you have to import both of these configs and export a similar object.

**Comment by phildotdev** [comment]
Thanks @marcorinck, this worked great on my project.

**Comment by rpascal** [comment]
I implemented the solution from @marcorinck, however I am getting this error: 
`TypeError: __WEBPACK_IMPORTED_MODULE_0_deepmerge__ is not a function`
Does anyone have any ideas? Thanks

**Comment by phildotdev** [comment]
@rpascal downgrade to deepmerge 1.5.2. it happens with v2 of the package.

**Comment by rpascal** [comment]
@fephil worked great thank you!
